export { ConfigurationModal, useConfigurationShortcut } from './ConfigurationModal'
export { useRegisterDirtyGuard } from './dirty-guard'
export type { DirtyGuard, SetDirtyGuard } from './dirty-guard'
export type { PaneId, PaneKind, PaneGroup, PaneDef } from './panes'
export { PANES, GROUP_LABELS, DEFAULT_PANE, getPane } from './panes'
